Repository legend-exp/LegendDSP.jl, pull requests merged in 2024-12, with the labels that each got.

#44 Bug Fix SiPM DSP
  src/dsp_sipm.jl
Labels: bug

#45 Add `DerivativeFilter`
  src/LegendDSP.jl
  src/derivative.jl
  test/test_derivative.jl
Labels: enhancement

#46 Bug fix derivative filter
  src/dsp_icpc.jl
Labels: bug, enhancement
